# Use the official Node.js 22.9.0 image as the base image
FROM node:22.9.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Next.js application for production
RUN npm run build

# Expose port 3000 for the Next.js application
EXPOSE 3000

# Set environment variable to tell Next.js it's in production
ENV NODE_ENV production

# Start the Next.js application in production mode
CMD ["npm", "start"]
